package botapi

import "strings"

// Bot API 10.1 method registry, generated from https://core.telegram.org/bots/api on 2026-06-23.
// The simulator uses this registry for case-insensitive routing and compatibility stubs.
var botAPIMethodNames = []string{
	"getUpdates",
	"setWebhook",
	"deleteWebhook",
	"getWebhookInfo",
	"getMe",
	"logOut",
	"close",
	"sendMessage",
	"forwardMessage",
	"forwardMessages",
	"copyMessage",
	"copyMessages",
	"sendPhoto",
	"sendLivePhoto",
	"sendAudio",
	"sendDocument",
	"sendVideo",
	"sendAnimation",
	"sendVoice",
	"sendVideoNote",
	"sendPaidMedia",
	"sendMediaGroup",
	"sendLocation",
	"sendVenue",
	"sendContact",
	"sendPoll",
	"sendChecklist",
	"sendDice",
	"sendMessageDraft",
	"sendChatAction",
	"setMessageReaction",
	"getUserProfilePhotos",
	"getUserProfileAudios",
	"setUserEmojiStatus",
	"getFile",
	"banChatMember",
	"unbanChatMember",
	"restrictChatMember",
	"promoteChatMember",
	"setChatAdministratorCustomTitle",
	"setChatMemberTag",
	"banChatSenderChat",
	"unbanChatSenderChat",
	"setChatPermissions",
	"exportChatInviteLink",
	"createChatInviteLink",
	"editChatInviteLink",
	"createChatSubscriptionInviteLink",
	"editChatSubscriptionInviteLink",
	"revokeChatInviteLink",
	"approveChatJoinRequest",
	"declineChatJoinRequest",
	"answerChatJoinRequestQuery",
	"sendChatJoinRequestWebApp",
	"setChatPhoto",
	"deleteChatPhoto",
	"setChatTitle",
	"setChatDescription",
	"pinChatMessage",
	"unpinChatMessage",
	"unpinAllChatMessages",
	"leaveChat",
	"getChat",
	"getChatAdministrators",
	"getChatMemberCount",
	"getChatMember",
	"getUserPersonalChatMessages",
	"setChatStickerSet",
	"deleteChatStickerSet",
	"getForumTopicIconStickers",
	"createForumTopic",
	"editForumTopic",
	"closeForumTopic",
	"reopenForumTopic",
	"deleteForumTopic",
	"unpinAllForumTopicMessages",
	"editGeneralForumTopic",
	"closeGeneralForumTopic",
	"reopenGeneralForumTopic",
	"hideGeneralForumTopic",
	"unhideGeneralForumTopic",
	"unpinAllGeneralForumTopicMessages",
	"answerCallbackQuery",
	"answerGuestQuery",
	"getUserChatBoosts",
	"getBusinessConnection",
	"getManagedBotToken",
	"replaceManagedBotToken",
	"getManagedBotAccessSettings",
	"setManagedBotAccessSettings",
	"setMyCommands",
	"deleteMyCommands",
	"getMyCommands",
	"setMyName",
	"getMyName",
	"setMyDescription",
	"getMyDescription",
	"setMyShortDescription",
	"getMyShortDescription",
	"setMyProfilePhoto",
	"removeMyProfilePhoto",
	"setChatMenuButton",
	"getChatMenuButton",
	"setMyDefaultAdministratorRights",
	"getMyDefaultAdministratorRights",
	"getAvailableGifts",
	"sendGift",
	"giftPremiumSubscription",
	"verifyUser",
	"verifyChat",
	"removeUserVerification",
	"removeChatVerification",
	"readBusinessMessage",
	"deleteBusinessMessages",
	"setBusinessAccountName",
	"setBusinessAccountUsername",
	"setBusinessAccountBio",
	"setBusinessAccountProfilePhoto",
	"removeBusinessAccountProfilePhoto",
	"setBusinessAccountGiftSettings",
	"getBusinessAccountStarBalance",
	"transferBusinessAccountStars",
	"getBusinessAccountGifts",
	"getUserGifts",
	"getChatGifts",
	"convertGiftToStars",
	"upgradeGift",
	"transferGift",
	"postStory",
	"repostStory",
	"editStory",
	"deleteStory",
	"answerWebAppQuery",
	"savePreparedInlineMessage",
	"savePreparedKeyboardButton",
	"editMessageText",
	"editMessageCaption",
	"editMessageMedia",
	"editMessageLiveLocation",
	"stopMessageLiveLocation",
	"editMessageChecklist",
	"editMessageReplyMarkup",
	"stopPoll",
	"approveSuggestedPost",
	"declineSuggestedPost",
	"deleteMessage",
	"deleteMessages",
	"deleteMessageReaction",
	"deleteAllMessageReactions",
	"sendSticker",
	"getStickerSet",
	"getCustomEmojiStickers",
	"uploadStickerFile",
	"createNewStickerSet",
	"addStickerToSet",
	"setStickerPositionInSet",
	"deleteStickerFromSet",
	"replaceStickerInSet",
	"setStickerEmojiList",
	"setStickerKeywords",
	"setStickerMaskPosition",
	"setStickerSetTitle",
	"setStickerSetThumbnail",
	"setCustomEmojiStickerSetThumbnail",
	"deleteStickerSet",
	"sendRichMessage",
	"sendRichMessageDraft",
	"answerInlineQuery",
	"sendInvoice",
	"createInvoiceLink",
	"answerShippingQuery",
	"answerPreCheckoutQuery",
	"getMyStarBalance",
	"getStarTransactions",
	"refundStarPayment",
	"editUserStarSubscription",
	"setPassportDataErrors",
	"sendGame",
	"setGameScore",
	"getGameHighScores",
}

var botAPIMethodCanonical = func() map[string]string {
	out := make(map[string]string, len(botAPIMethodNames))
	for _, name := range botAPIMethodNames {
		out[strings.ToLower(name)] = name
	}
	return out
}()

func canonicalBotAPIMethod(method string) (string, bool) {
	canonical, ok := botAPIMethodCanonical[strings.ToLower(method)]
	return canonical, ok
}

func isGenericSendMessageMethod(method string) bool {
	switch method {
	case "forwardMessage",
		"sendAudio",
		"sendLivePhoto",
		"sendDocument",
		"sendVideo",
		"sendAnimation",
		"sendVoice",
		"sendVideoNote",
		"sendPaidMedia",
		"sendLocation",
		"sendVenue",
		"sendContact",
		"sendPoll",
		"sendChecklist",
		"sendDice",
		"sendSticker",
		"sendGame":
		return true
	default:
		return false
	}
}
